# Units file
units: "units.tsv"

# Dirs
TMPDIR: "/home/andres/Escritorio/bioinfo_hematology_unit/novalign_optimization/tmp_files" # Temporary dir.

# Wrappers
wrapper:
  qc: "v7.2.0/bio/fastqc"
  multiqc: "v7.2.0/bio/multiqc"

# Environments
envs: 
  picard: "/home/andres/Escritorio/bioinfo_hematology_unit/novalign_optimization/workflow/envs/picard.yaml"
  samtools: "/home/andres/Escritorio/bioinfo_hematology_unit/novalign_optimization/workflow/envs/samtools.yaml"
  fastqc: "/home/andres/Escritorio/bioinfo_hematology_unit/novalign_optimization/workflow/envs/fastqc.yaml"
  fastq_screen: "/home/andres/Escritorio/bioinfo_hematology_unit/novalign_optimization/workflow/envs/fastq_screen.yaml"
  qualimap: "/home/andres/Escritorio/bioinfo_hematology_unit/novalign_optimization/workflow/envs/qualimap.yaml"
  multiqc: "/home/andres/Escritorio/bioinfo_hematology_unit/novalign_optimization/workflow/envs/multiqc.yaml"

# Human genome
hg_version: "hg38"

# Library type
library: "WGS_SHORT_INSERT_lib""

# Squencing platform
seq_platform: "DNBSEQ"

# Sequencing run
seq_run: "F26A430000256_HOMubfrR"

# Reference genome.
reference:
  fasta: "path/to/reference.fasta"
  index: "workflow/resources/genome/hg38_dbsnp146_M5.ndx"

# Reads. TODO: Identify if they could be inferred from the units file.
read: ["R1", "R2"]

# Parameters
parameters:

  fastqc:

    extra: "--adapters workflow/resources/adapters/adapter_list.txt"

  fastq_screen:

    fastq_screen_db: "/home/andres/Escritorio/bioinfo_hematology_unit/resources/fastq_screen/FastQ_Screen_Genomes"
    config: "workflow/templates/fastq_screen.conf"
    aligner: bowtie2
    extra: ""

  novoalign:

    extra: ""

  novosort:

    extra: "--markduplicates"

  add_replace_rg:

    extra: "CREATE_INDEX=true SORT_ORDER=coordinate"

  qualimap:

    genome: HUMAN
    annotation: "path/to/annotation.gtf"
    extra_single: "-hm 3 -nr 1000 " # -p strand-specific-forward for 3' RNa-seq
    extra_multi: ""

  samtools_qc:

    extra_stats: ""

# Resources.
resources:
    default:
        threads: 2
        mem_mb:  2000
        runtime: 170

    fastqc:
        threads: 8
        mem_mb:  2970
        runtime: 60

    fastq_screen:
        threads: 8
        mem_mb:  2970
        runtime: 60
    
    novoalign:
        threads: 30
        mem_mb:  20000
        runtime: 10
      
    novosort:
      threads: 2
      mem_mb: 20000
      runtime: 10

    add_replace_rg:
        threads: 2
        mem_mb:  3000
        runtime: 10
      
    qualimap:
      threads: 8
      mem_mb: 16384
      runtime: 10

    samtools_qc:
      threads: 5
      mem_mb: 3000
      runtime: 10