# Samples
SAMPLES: ["S17"]
LANES: ["L000"]

# Dirs
TMPDIR: "/home/andres/Escritorio/bioinfo_hematology_unit/novalign_optimization/tmp_files" # Temporary dir.
genome_index: "workflow/resources/hg38_dbsnp146_M5.ndx" # Genome dir. 

# Environments
envs: 
  picard: "/home/andres/Escritorio/bioinfo_hematology_unit/novalign_optimization/workflow/envs/picard.yaml"
  samtools: "/home/andres/Escritorio/bioinfo_hematology_unit/novalign_optimization/workflow/envs/samtools.yaml"

# Human genome
hg_version: "hg38"

# Panel
panel: "Adaptive"

# Squencing platform
seq_platform: "Illumina"

# Parameters
parameters:

  novoalign:

    extra: ""

  novosort:

    extra: "--markduplicates"

  add_replace_rg:

    extra: "CREATE_INDEX=true SORT_ORDER=coordinate"
  
  merge_bams:

    extra: "-c -O BAM"


# Resources.
resources:
    default:
        threads: 2
        mem_mb:  2000
        runtime: 170

    novoalign:
        threads: 30
        mem_mb:  20000
        runtime: 10
      
    novosort:
      threads: 2
      mem_mb: 20000
      runtime: 10

    add_replace_rg:
        threads: 2
        mem_mb:  3000
        runtime: 10

    merge_bams:
        threads: 5
        mem_mb:  8000
        runtime: 10